apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publish-evidence-item

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  id-token: read

jobs:
  testAction:
    steps:
    - id: testAction
      name: Test publish-evidence-item action
      uses: .
      with:
        content: |
          ## Test markup and property rendering
          - Run ID: ${{ cloudbees.run_id }}