apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and Test
    steps:
      - name: Checkout code
        uses: docker://alpine:3.18
        shell: sh
        run: |
          apk add --no-cache git
          https://github.com/vimanthan3/demo1.git

      - name: Build project
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          apk add --no-cache maven
          echo "Workspace contents before build:"
          ls -l /cloudbees/workspace
          cd spring-petclinic-config-server && mvn clean install
          echo "Workspace contents after build:"
          ls -l

      - name: Show commit-info.md
        uses: docker://alpine:3.18
        shell: sh
        run: |
          echo "Displaying commit-info.md content:"
          cat /cloudbees/workspace/commit-info.md
          echo "End of commit-info.md content"
