apiVersion: automation.cloudbees.io/v1alpha1
kind: Task
metadata:
  name: capture-commit-message-task
spec:
  steps:
    - name: capture-commit-message
      image: golang:1.20.3-alpine3.17
      script: |
        #!/bin/sh
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" > /tekton/results/commit-message