apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publish-evidence-item

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  testAction:
 
    name: Clone Repository
    command:
          - git clone https://github.com/vimanthan3/sampleproject.git /tmp/source
          - cd /tmp/source
          - git checkout main
          - id: test-action
            name: Test publish-evidence-item action
            command:
          - if [ ! -f /tmp/source/action.yaml ]; then
              echo "action.yaml not found!"
              exit 1
            fi
          - echo "Running Test publish-evidence-item action"
          - echo "## Test markup and property rendering"
          - echo "- Run ID: ${{ cloudbees.run_id }}"
          - echo "- Color test: <span style=\"color:green\">This text should be green</span>"
          - echo "- [backend.tar](https://ourcompany.com/repo/backend.tar)"
