apiVersion: automation.cloudbees.io/v1alpha1
kind: Workflow
metadata:
  name: my-workflow
spec:
  triggers:
    - type: push
      branches:
        - 'main'
  jobs:
    - name: build
      steps:
        - name: Say hello
          image: golang:1.20.3-alpine3.17
          shell: sh
          run: |
            echo "hello world"

    - name: capture-commit-message
      needs: build
      steps:
        - name: Capture Commit Message
          image: alpine/git
          shell: sh
          run: |
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" > /workspace/commit-message.env

    - name: publish-evidence
      needs: capture-commit-message
      steps:
        - name: Publish workflow evidence item
          image: curlimages/curl
          shell: sh
          run: |
            echo "## Test markup and property rendering" > /workspace/evidence.txt
            echo "- Run ID: ${{ cloudbees.run_id }}" >> /workspace/evidence.txt
            echo "- Commit Message: $(grep COMMIT_MESSAGE /workspace/commit-message.env | cut -d'=' -f2)" >> /workspace/evidence.txt
            curl -X POST -H "Content-Type: text/plain" --data-binary @/workspace/evidence.txt http://your-evidence-service/api/publish
