apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publish-evidence-item

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  testAction:
    steps:
    - id: testAction
      name: Test publish-evidence-item action
      uses: .
      with:
        content: |
          ## Test markup and property rendering
          - Run ID: ${{ cloudbees.run_id }}
          - Color test: <span style="color:green">This text should be green</span>
          - [backend.tar](https://ourcompany.com/repo/backend.tar)
