apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

  evidence:
    needs: build
    steps:
      - name: Get Commit Info
        id: commit_info
        uses: docker://alpine/git:latest
        shell: sh
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV

      - name: Publish workflow evidence item
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## Test markup and property rendering
            - Run ID: ${{ cloudbees.run_id }}
            - Commit Message: ${{ steps.commit_info.outputs.COMMIT_MESSAGE }}
            
            ## Workflow Evidence
            | Property      | Value                                         |
            |---------------|-----------------------------------------------|
            | Commit ID     | ${{ steps.commit_info.outputs.COMMIT_ID }}   |
            | Commit Message| ${{ steps.commit_info.outputs.COMMIT_MESSAGE }}|
          format: MARKDOWN
        env:
          cloudbees.api.token: ${{ cloudbees.api.token }}
          cloudbees.api.url: ${{ cloudbees.api.url }}
          step.id: ${{ step.id }}