apiVersion: automation.cloudbees.io/v1alpha1
kind: Task
metadata:
  name: publish-evidence-task
spec:
  params:
    - name: COMMIT_MESSAGE
      type: string
  steps:
    - name: publish-evidence
      image: cloudbees-io/publish-evidence-item:latest
      script: |
        #!/bin/sh
        echo "## Test markup and property rendering"
        echo "- Run ID: $(context.pipelineRun.name)"
        echo "- Commit Message: ${COMMIT_MESSAGE:-'No commit message available'}"