apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

  evidence:
    needs: build
    steps:
      - name: Prepare and Post Evidence
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh  
        run: |
          # Prepare content to be used in the JSON
          PREPARED_CONTENT=$(echo "$CONTENT" | sed 's/"/\\"/g' | sed 's/$/\\n/g' | tr -d '\n')
          
          # Make Platform API call to post workflow evidence item
          response=$(curl --fail-with-body -X 'POST' "$URL/v1/workflows/artifact" -H "Authorization: Bearer $JWT" -H 'Content-Type: application/json' --data-binary '{"stepId": "'"$STEP_ID"'", "evidence": {"value": "'"$PREPARED_CONTENT"'", "format": "'"$FORMAT"'"}}') || command_failed=1
          
          # Check curl exit code
          if [ ${command_failed:-0} -eq 1 ]; then
            echo "Platform API call failed with error: '$response'"
            exit 1
          fi
    env:
          STEP_ID: ${{ step.id }}
          CONTENT: ${{ inputs.content }}
          FORMAT: ${{ inputs.format }}
          JWT: ${{ cloudbees.api.token }}
          URL: ${{ cloudbees.api.url }}
