apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    steps:
      - name: Checkout code
        uses: docker://alpine:latest
        shell: sh
        run: |
          apk add --no-cache git
          git clone https://github.com/cashokannamalai/spring-petclinic-config-server.git

      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          ls -l /cloudbees/workspace
          cd spring-petclinic-config-server