apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publish-evidence-item
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo "Current commit ID: $GITHUB_SHA"  # Access the commit ID
